[package]
name = "bad-shark"
version = "0.1.2"
edition = "2024"
authors = ["Akari Harada <akaritwo0two@gmail.com>"]
repository = "https://github.com/Akari202/bad-shark"
license = "GPL-3"

[dependencies]
bytemuck = { version = "1.19.0", features = ["derive"] }
cfg-if = "1.0.0"
cgmath = "0.18.0"
eframe = { version = "0.33.2", features = ["persistence"] }
env_logger = "0.11.5"
itertools = "0.13.0"
log = "0.4.22"
pollster = "0.3.0"
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive"] }
vec-utils = { path = "../vec-utils/vec-utils/", version = "0.2.1", features = [
  "serde"
] }
wasm-bindgen = "0.2.95"
web-sys = "0.3.72"
wgpu = "22.1.0"
winit = { version = "0.29.15", features = ["rwh_05"] }
